version: 2
jobs:
  test-driver-service:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout     
      - run:
          name: Install dependencies
          command: cd alten.backend/services/driver-service && npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm test
  
workflows:
  version: 2
  ultimate_pipeline:
    jobs:
      - test-driver-service
      